@props([
    'name',
    'alt' => '',
    'sizes' => '100vw',
    'loading' => 'lazy',
    'priority' => false,
])

@php
    // Derivatives are generated by `npm run images` into public/img/r. Anything
    // without them still resolves to the full-size file.
    //
    // The listing is read once per request rather than stat-ing four paths per
    // image — the home page alone renders sixty of these.
    $derivatives = once(function (): array {
        $dir = public_path('img/r');

        if (! is_dir($dir)) {
            return [];
        }

        return array_flip(array_filter(scandir($dir), fn (string $f) => str_ends_with($f, '.jpg')));
    });

    $widths = [480, 800, 1200, 1800];

    $available = array_values(array_filter(
        $widths,
        fn (int $w) => isset($derivatives[$name.'-'.$w.'.jpg'])
    ));

    $srcset = fn (string $ext) => implode(', ', array_map(
        fn (int $w) => asset('img/r/'.$name.'-'.$w.'.'.$ext).' '.$w.'w',
        $available
    ));

    $fallbackWidth = $available ? (in_array(1200, $available, true) ? 1200 : end($available)) : null;
    $fallback = $fallbackWidth
        ? asset('img/r/'.$name.'-'.$fallbackWidth.'.jpg')
        : asset('img/'.$name.'.jpg');
@endphp

{{-- display:contents so the img keeps inheriting the parent's layout and every
     existing utility class on it still applies. --}}
<picture class="contents">
    @if ($available)
        <source type="image/webp" srcset="{{ $srcset('webp') }}" sizes="{{ $sizes }}">
        <source type="image/jpeg" srcset="{{ $srcset('jpg') }}" sizes="{{ $sizes }}">
    @endif
    <img src="{{ $fallback }}"
         alt="{{ $alt }}"
         @if ($priority) fetchpriority="high" decoding="async" @else loading="{{ $loading }}" decoding="async" @endif
         {{ $attributes }}>
</picture>
